### ISSUE TITLE
Overlaps with Navigation API

### ISSUE THREAD

**Issue by DerGernTod** [WICG/soft-navigations#16]
First of all, I think that having the ability to detect soft navigations and the correlated performance entries (web vitals) is very helpful. I'm just concerned that this overlaps too much with the Navigation API.

The Navigation API already provides entries for soft navigations. What exactly sets this spec apart? It feels like there's two things that solve the same problem now, especially since the Navigation API is still not living standard and could be enriched with the id that would correlate to the respective performance entries.

What is the purpose of this spec, especially compared to the Navigation API spec? What sets it apart?

**Comment by yoavweiss** [comment]
This doesn't really overlap with the Navigation API. This mechanism works well with the Navigation API as well as the history API to heuristically detect same-document navigations that should also be considered soft navigations. I'll add a section to the explainer outlining that.

**Comment by yoavweiss** [comment]
> The Navigation API already provides entries for soft navigations.

If you're talking about [NavigationHistoryEnrty](https://html.spec.whatwg.org/multipage/nav-history-apis.html#the-navigationhistoryentry-interface), they provide a very different role than performance entries, and are not used for monitoring performance, but (IIUC) to enable control over navigations.

**Comment by yoavweiss** [comment]
FWIW, added a FAQ item that touches on this a bit in https://github.com/WICG/soft-navigations/pull/23

Let me know if there are still clarifications to be made.

**Comment by yoavweiss** [comment]
Closing as I believe this was addressed. Let me know if that's not the case.
