### ISSUE TITLE
What's the epoch for events after a soft navigation

### ISSUE THREAD

**Issue by andydavies** [WICG/soft-navigations#2]
Will the epoch for events after a soft navigation still be navigationStart, or will the epoch be reset and thus impact performance.now?

I'm assuming the epoch will still be navigationStart but it might be worth clarifying in the explainer

**Comment by yoavweiss** [comment]
If you're talking about the timeOrigin, it will not be modified by a soft navigation, and continue to be based on the landing navigation's start time. The way to consider the soft navigation's start time, is to take an entry's navigation ID, find the corresponding SoftNavigationEntry and look at its start time.
[One of the examples](https://github.com/yoavweiss/soft-navigations#correlating-paints-with-a-soft-navigation) demonstrates that. Let me know if you think further clarifications are needed.

**Comment by yoavweiss** [comment]
Closing as I think I answered the question, but let me know if you think otherwise! :)
