### ISSUE TITLE
Address Security / Privacy issues

### ISSUE THREAD

**Issue by rowan-m** [WICG/soft-navigations#9]
It would be helpful to have a section on any security and privacy issues considered in this. I don't see a mention here or on https://github.com/w3c/performance-timeline

The initial thing I'm unclear on is if clearing storage also clears navigations? Asking as an SPA clearly does blur the boundary (as the proposal highlights!) on a navigation and I'm unsure about what state would persist there.

**Comment by yoavweiss** [comment]
Thanks for filing this!! This made me think deeply about the information exposed, add tests that verify there isn't anything unpredictable and document it all. I'll push a PR shortly.



> The initial thing I'm unclear on is if clearing storage also clears navigations?

This is not something we've considered. Soft navigations still maintain the same `window` element with all its (ephemeral) state, so it's unclear to me how clearing storage is related to soft navigations.

**Comment by yoavweiss** [comment]
https://github.com/WICG/soft-navigations#privacy-and-security-considerations now contains what I had in mind on information this proposal exposes and mitigations.

**Comment by rowan-m** [comment]
Super helpful, thank you!
